apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: ireh17/docker101tutorial:latest # 이 부분이 Actions에서 수정됨
        ports:
        - containerPort: 80
